### ISSUE TITLE
S07: `@a.push: @b` pushes one, not @b.elems values

### ISSUE THREAD

**Issue by uvtc** [perl6/specs#104]
The lines in S07:

    @a.push: @b;            # pushes @b.elems values to @a
    @a.push: @b,;           # same, trailing comma doesn't make > 1 argument

appear to be incorrect. For me, it pushes `@b` as one value onto `@a`:

~~~
> my @a = <a b>
[a b]
> @a
[a b]
> my @b = <x y z>
[x y z]
> @a.push: @b
[a b [x y z]]
~~~

As opposed to `[a b x y z]`, which is what I think the document suggests.

**Comment by uvtc** [comment]
Ooof. Or maybe I'm reading it incorrectly, or maybe the doc is right and Rakudo is doing something different.

**Comment by zoffixznet** [comment]
Seems that part of the spec hasn't been updated since GLR. Rakudo's behaviour is correct.

**Comment by vendethiel** [comment]
yeah, that's why we have `@a.append:` now.

**Comment by MadcapJake** [comment]
Look to the [docs](http://doc.perl6.org/routine/push) first and the synopses second as the docs appear to reflect the current rakudo behavior.

**Comment by jnthn** [comment]
At the time S07 was written, push followed the one arg rule. Then it changed to not do so, and it's now not a good example. I think append would be a better example for S07 to use now.

**Comment by uvtc** [comment]
Not sure how the doc should be changed (or if there are any other post-GLR updates required) --- I'm still just learning.

@MadcapJake , thanks for the doc tip. @vendethiel nice, I see that there's a nice symmetrical prepend/append pair.
