### ISSUE TITLE
S32: "seek" talks about bytes, "tell" uses octets

### ISSUE THREAD

**Issue by pmqs** [perl6/specs#85]
**seek** says this

```
Move the file pointer to $position. The meaning of this position is always in "bytes", 
```

**tell** says this

```
Returns the position of the file pointer in number of "octets".
```

I assume **bytes** should be used in both?

**Comment by grondilu** [comment]
octets is the French for bytes.  No idea why someone used this word here.

**Comment by grondilu** [comment]
Just checked the guys on IRC.  Apparently the word "octet" was used whenever it was important to stress on that we're talking about "bytes of 8 bits", for on olg machines bytes were sometimes of different lengths (6,7,9 bits...).  Not sure if we should disambiguate here.

**Comment by polettix** [comment]
I would actually prefer to see it spelled as *octets* in both places -
http://en.wikipedia.org/wiki/Octet_%28computing%29

Nowadays *bytes* is probably fine too, though.

2015-02-15 16:26 GMT-05:00 pmqs <notifications@github.com>:

**Comment by pmqs** [comment]
The main point of this issue is consistency.

A common use case (in fact the one I'm having difficulty with) is where you remember the value (X) returned from **tell**,  then **seek** to a different offset. Finally you return back to the original location by seeking to "X".

So in this common use-case the value returned from **tell** will ultimately be used as a parameter to **seek**. I would then have expected that **tell** and **seek** use the same "unit" for offset. Having them different will be a cause of confusion.

The reason I suggested using bytes was because the only place I see the term octets used at all in S32-IO  is with **tell**. Everywhere else uses the term bytes.

**Comment by patch** [comment]
In modern usage, I only hear Perl programmers talking about octets and distinguishing them from bytes. Considering that you’re unlikely to find a byte that’s not eight bits nowadays, I think the distinction just adds confusion to a topic that junior developers already have trouble understanding. Additionally, the Unicode Standard now uniformly uses the term *bytes* instead of *octets*, as described in the [Glossary of Unicode Terms](http://unicode.org/glossary/) and included below.

> [*Octet*](http://unicode.org/glossary/#octet). An ordered sequence of eight bits considered as a unit. The Unicode Standard follows current industry practice in referring to an octet as a *byte*. (See [*byte*](http://unicode.org/glossary/#byte).)

> [*Byte*](http://unicode.org/glossary/#byte). (1) The minimal unit of addressable storage for a particular computer architecture. (2) An octet. Note that many early computer architectures used bytes larger than 8 bits in size, but the industry has now standardized almost uniformly on 8-bit bytes. The Unicode Standard follows the current industry practice in equating the term *byte* with *octet* and using the more familiar term *byte* in all contexts. (See [*octet*](http://unicode.org/glossary/#octet).)

**Comment by pmqs** [comment]
Duh! 
Was looking at perl6/doc rather that perl6/spec. 
Issue not present in perl6/doc bit is in perl6/spec.

**Comment by pmqs** [comment]
Closing - create pull request #124 to deal with the issue.
